### ISSUE TITLE
Build failing on network access

### ISSUE THREAD

**Issue by jwheare** [flathub/com.irccloud.desktop#6]
https://flathub.org/builds/#/builders/8/builds/4366

Not sure how to debug what request this is.

Any ideas @nedrichards @barthalion?

```
error /run/build/irccloud/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /run/build/irccloud/node_modules/electron
Output:
RequestError: getaddrinfo EAI_AGAIN github.com
    at ClientRequest.<anonymous> (/run/build/irccloud/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.origin.emit (/run/build/irccloud/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by barthalion** [comment]
Oops, missed the notification somehow. I'll have a look today or tomorrow morning.

**Comment by barthalion** [comment]
I don't see anything obvious at first glance. @refi64 any tips? Electron is downloaded as part of generated-sources.json, maybe it's wrong version? Not sure how to check it though.

**Comment by barthalion** [comment]
@jwheare Looks like passing `--xdg-layout` to the node generator is required these days.

**Comment by refi64** [comment]
Mostly yeah, I want to see if it can be changed by detecting the electron
package versions but haven't had time to check yet.
